### ISSUE TITLE
Error after attempting to authorize with OAuth credentials.

### ISSUE THREAD

**Issue by Smellyhobo101** [nithinmurali/pygsheets#100] opened 2017-07-21 00:43 UTC
After I pygsheets.authorize(), I get the webpage and log in to my google account, then I get this error:

> Authentication successful.
> Storing credentials to C:\Users\[redacted]\sheets.googleapis.com-python.json
> Traceback (most recent call last):
>   Python Shell, prompt 3, line 1
>   File "c:\Python3.6.0\Lib\site-packages\pygsheets\client.py", line 550, in authorize
>     rclient = Client(oauth=credentials, **client_kwargs)
>   File "c:\Python3.6.0\Lib\site-packages\pygsheets\client.py", line 77, in __init__
>     self._fetch_sheets()
>   File "c:\Python3.6.0\Lib\site-packages\pygsheets\client.py", line 90, in _fetch_sheets
>     results = self._execute_request(None, request, False)
>   File "c:\Python3.6.0\Lib\site-packages\pygsheets\client.py", line 421, in _execute_request
>     response = request.execute()
>   File "c:\Python3.6.0\Lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "c:\Python3.6.0\Lib\site-packages\googleapiclient\http.py", line 835, in execute
>     method=str(self.method), body=self.body, headers=self.headers)
>   File "c:\Python3.6.0\Lib\site-packages\httplib2\__init__.py", line 690, in set
>     f = open(cacheFullPath, "wb")
> builtins.FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[redacted]\\AppData\\Local\\Temp\\4836476a-32ff-47df-b186-dca85e32c852\\www.googleapis.com,drive,v3,files,corpora=user&pageSize=500&fields=files%28id%2C+name%29&q=mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27&supportsTeamDrives=false&includeTeamDriveItems=fal,6fa737f4e6c871f0b9ea9ea38467b8b6'

Happens every time I pygsheets.authorize()

**Workaround** : turn cache off with param `no_cache=True` in authorize

**Comment by nithinmurali** [comment] 2017-07-21 07:22
try turning cache off with param `no_cache=True`

**Comment by Smellyhobo101** [comment] 2017-07-22 05:35
`no_cache=True` worked, thanks!

That path does exist, and I did check that the folder its trying to access in the temp folder exists as well. It's just empty for some reason.

**Comment by stascrash** [comment] 2017-07-24 22:07
Thanks, this worked for me too.

**Comment by bay007** [comment] 2017-08-17 05:08
work for me.. but Aditional, i Change my scope to  ['https://www.googleapis.com/auth/spreadsheets',
             'https://www.googleapis.com/auth/drive']
check the code 
`credentials_sheets = {
            "type": creds_google['type'],
            "project_id": creds_google['project_id'],
            "private_key_id": creds_google['private_key_id'],
            "private_key": creds_google['private_key'],
            "client_email": creds_google['client_email'],
            "client_id": creds_google['client_id'],
            "auth_uri": creds_google['auth_uri'],
            "token_uri": creds_google['token_uri'],
            "auth_provider_x509_cert_url": creds_google['auth_provider_x509_cert_url'],
            "client_x509_cert_url": creds_google['client_x509_cert_url']
        }

        

        # use creds to create a client to interact with the Google Drive API
        scope = ['https://www.googleapis.com/auth/spreadsheets',
                 'https://www.googleapis.com/auth/drive']
        creds = ServiceAccountCredentials.from_json_keyfile_dict(
            credentials_sheets, scope)
        client = pygsheets.authorize(credentials=creds, no_cache=True)

        sheet = client.open("name_sheet").sheet1

        # insert a row into a spreadsheet
        index = 1
        row_insert = data
        row = []
        for llave, valor in row_insert.items():
            row.append(valor)

        sheet.insert_rows(index, values=row)`

**Comment by kankri** [comment] 2017-11-04 15:31
The problem is that the generated cache file name exceeds the maximum path name length of Win32 API (260 characters). I verified this by changing ```pygsheets.client.Client()``` to prepend "\\?\" to the cache directory name and the error disappeared.

See [Naming Files, Paths, and Namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) for limits on allowed characters and path name lengths on Win32 API and how to use the NT namespace to avoid the limits and forbidden filenames like "aux.py".

**Comment by nithinmurali** [comment] 2017-11-06 23:16
pushed a fix to staging branch. It would be great if someone could test this is a windows box.

**Comment by yoshifan** [comment] 2017-12-02 03:16
I ran into this issue on Windows 7 64-bit, using a service account to authorize in pygsheets 1.1.3. Tried the fix by monkey-patching with 84d1a01e8440e6f960ea6edc4f0799563fe88d96, and it indeed fixed the issue. I then also tried from the staging branch and that worked.

**Comment by nithinmurali** [comment] 2017-12-03 13:36
Cool. closing the issue.

**Closed by nithinmurali** 2017-12-03 13:36 UTC
Labels: bug

**Comment by steveoh** [comment] 2018-02-26 23:59
What version is will this be fixed in? 1.1.3 still has the issue without `no_cache=True`.

**Comment by nithinmurali** [comment] 2018-02-27 17:09
This is fixed in the trunk. will be fixed in next version 1.2.0
