### ISSUE TITLE
exceeds grid limits. Max rows: 2280, max columns: 178

### ISSUE THREAD

**Issue by jainraje** [nithinmurali/pygsheets#124] opened 2017-09-22 04:52 UTC
Recently I am getting a "exceeds grid limits. Max rows: 2280, max columns: 178" error message. My actual data frame is 2306 rows x 105 cols (242,130 cells). Please advise. thx.

Here is exception stack:
File "/Users/rajeev/Documents/Code/Python/smdb/smdb_llio.py", line 357, in google_sheet_write_fit_false
    wks.set_dataframe(df, start, fit=False)
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/pygsheets/worksheet.py", line 780, in set_dataframe
    self.update_cells(crange=crange, values=values)
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/pygsheets/worksheet.py", line 431, in update_cells
    self.client.sh_update_range(self.spreadsheet.id, body, self.spreadsheet.batch_mode, parse=parse)
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/pygsheets/client.py", line 374, in sh_update_range
    self._execute_request(spreadsheet_id, final_request, batch)
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/pygsheets/client.py", line 418, in _execute_request
    response = request.execute()
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/rajeev/anaconda/lib/python3.5/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400

**Comment by willianvargas** [comment] 2017-09-22 05:28
I am getting this error too. The probably problem is because the spreadsheet is too heavy. I think we can investigate more about this.

**Comment by jainraje** [comment] 2017-09-22 06:04
my understanding is max number of cells is approx. 400k (i.e. num rows x num cols). I've been doing the same sized write for several weeks w/ no errors. only today i'm getting this exception for writes much less than 400k cells. i'm thinking google changed something....

**Comment by jainraje** [comment] 2017-09-23 16:03
additional info:
- size of DF: 2463 rows x 105 cols (grid size = 258615 cells)
- 'set_dataframe' call uses fit=False. 
- Error message calculates grid limits as (2280x179): 405840 cells.
- my DF is less than the limit so I'm wondering why the error message?
- i performed same write to a empty new sheet (so I don't think the spreadsheet is *heavy*)
- pertinent line of code:
import httplib2
http_client = httplib2.Http(timeout=50)
gc = pygsheets.authorize(outh_file=oauth_file, http_client=http_client, retries=5)
sh = gc.open(spreadsheet)
pygsheets.client.GOOGLE_SHEET_CELL_UPDATES_LIMIT = 40000
start = (1, 1)
wks = sh.worksheet_by_title(worksheet)wks.set_dataframe(df, start, fit=False)
wks.rows = df_num_rows(df) + 1

- Error message: 
File "/Users/rajeev/anaconda/lib/python3.5/site-packages/googleapiclient/http.py", line 840, in execute raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1fi0JaIFPKtPM2cIMeiPmT3ynzK8rW7tHcyzwrcFznFE/values/MainDB%21A2281%3ADB2467?valueInputOption=USER_ENTERED&alt=json returned "Range (MainDB!A2281:DB2467) exceeds grid limits. Max rows: 2280, max columns: 178">
 
nithin - will you please comment or help?

Thx!

**Comment by jainraje** [comment] 2017-09-23 16:12
I seemed to have solved the problem by setting wks.row before the set_dataframe call:

wks.rows = df.shape[0]
wks.set_dataframe(df, start, fit=False)

the DF write now completes without an error.

**Comment by jainraje** [comment] 2017-09-23 16:16
@willianvargas - do you want to test out if above solution resolves your situation?

we can let nithin comment and then close this issue.

**Comment by nithinmurali** [comment] 2017-09-23 16:45
Hi @jainraje, sorry for the delay. The `Range exceeds limits` error happens because you are writing to what is more than the sheets size. you see the rows of your df(2463) > size of your sheet(2463). So if you use the `fit=True` options it should work (that's actually the one of use of that options). But i guess here you don't wanna fit both dimensions, so resizing before writing should work.

**Comment by nithinmurali** [comment] 2017-09-23 17:00
I think we should give more meaningful error here, as this big stack-trace might confuse ppl. or maybe check if the df fits in sheets and thow an exception.

**Comment by jainraje** [comment] 2017-09-24 16:10
m using the fit=false specifically because i have existing columns/data to right of the range and resizing the rows on subsequent writes. The writes ae working well once i set the wks.rows before the set_dataframe. Will be intreresting to see if this solves @willianvargas issue. Let me know if you would like me to test any specific scenarios...thxs for your very good support.

**Comment by willianvargas** [comment] 2017-10-01 21:15
@jainraje I will test with your solution this week, so I will send you some feedback. I will also test with `fit=True`.

**Comment by willianvargas** [comment] 2017-10-09 14:32
@jainraje Unfortunately I can no longer reproduce this error with `set_dataframe` method. But my requests with `update_cells` were getting this error too. I solved the problem just adding the param `extend=True`. @nithinmurali I think we can close this issue, since this was just bad usage of methods.

**Closed** 2017-10-09 14:40 UTC

**Comment by sanjmeh** [comment] 2020-06-28 10:14
Is there any solution / workaround as I still get this error while reading a large google sheet using R package `googlesheets4`? Was it found to be a total cell limits crossed? Can someone drop in here a closure? Thanks.

**Comment by nithinmurali** [comment] 2020-06-29 07:40
@sanjmeh this is specific to `pygsheets`. It happened because users were trying to write cells which dosen't exist. It shouldn't happen when reading though. please check the docs of `googlesheets4`.

**Comment by ChandlerTayek** [comment] 2021-05-22 00:58
I'm experiencing the same error but only for getting all values from a worksheet. These happen when trying to execute: 
`.get_as_df()`, `.get_all_values()`. @nithinmurali  I'm sure I'm miss using this library somehow but I can't figure this out. Any help is much appreciated as I love this library and really don't want to do a hack to read in my spreadsheet as a dataframe.

**Comment by nithinmurali** [comment] 2021-05-22 01:35
@ChandlerTayek can you give a code to exactly reproduce this issue from scratch? I am unable to reproduce this. 
If you could share a sample spreadsheet that produces this issue to pygsheettest@gmail.com, and share the code, will also work.

**Comment by ChandlerTayek** [comment] 2021-05-22 01:53
@nithinmurali  I just sent you a .ipynb and associated spreadsheet to reproduce the issue. I'll be watching my mail and this thread closely if you need help. I will be investigating more to find the source of the issue as well.

**Comment by nithinmurali** [comment] 2021-05-22 11:09
@ChandlerTayek I have published a fix in staging. please lemme know if it works.

**Comment by ChandlerTayek** [comment] 2021-05-23 18:39
@nithinmurali I can confirm that your patch worked for me. Thank you so much. Next time I will just try to fix it myself and submit a pull request.
