### ISSUE TITLE
A/O October 3rd  spreadsheet.share emailMessage not sending emails out?

### ISSUE THREAD

**Issue by devin-moonrise** [nithinmurali/pygsheets#382] opened 2019-10-08 15:22 UTC
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
the emailMessage argument to spreadsheet.share(...) stopped sending emails out for me on October 3rd. Tested a couple different things (new sheets, edited sheets, etc) and no dice.

Actual sharing behavior working fine.

**System Information**
 - OS: [e.g. iOS]: AWS/Linux.
 - pygsheets version : 2.0.2
 - pygsheets installed from (github or pypi): pypi

**Comment by nithinmurali** [comment] 2019-10-08 18:16
No changes in pygsheets sharing code. Probably a change in api side. needs verification.

**Comment by devin-moonrise** [comment] 2019-10-08 18:20
That was my gut instinct.
I don't think I can verify past the testing I've done on a couple different sheets on my end. Any ways I can help?

**Comment by nithinmurali** [comment] 2019-10-08 18:31
i don't see any immediate changes in the api. Can you check with the try api feature [here](https://developers.google.com/drive/api/v3/reference/permissions/create), If the email notification is getting sent in your case?

**Comment by devin-moonrise** [comment] 2019-10-08 20:33
Having problems getting the API tester to recognize the existence of the sheets I'm using. Think it may be a service account vs. logged in account issue...

**Comment by nithinmurali** [comment] 2019-10-09 05:35
Just tested the share method with my personal sheet, seems to be working good. Does your sheet has any special properties? like in a team drive or something?

**Comment by devin-moonrise** [comment] 2019-10-09 11:24
Yeah -- They are all created/owned by a service account.

**Comment by nithinmurali** [comment] 2019-10-09 16:56
Okay, I can confirm this behavior with sheets owned by service account. The sheet is getting shared but the api is ignoring the `sendNotificationEmail` param and `emailMessage` param.

**Comment by devin-moonrise** [comment] 2019-10-09 16:58
Yup -- Describes my situation exactly -- Share was still working fine under the hood, just no notification sent.

Anything I can try to do to help with a fix?

> Okay, I can confirm this behavior with sheets owned by service account. The sheet is getting shared but the api is ignoring the `sendNotificationEmail` param and `emailMessage` param.

**Comment by nithinmurali** [comment] 2019-10-09 17:38
I don't think anything can be done my our side. As the api call is getting made correctly. 

Some things you can try:

- try some other library and see if you face the same issue (If this works please report here.)
- use a non-service account (maybe create a dummy account solely for this?)
- If all other fails, raise a bug request with google api.

**Comment by nithinmurali** [comment] 2019-10-10 13:08
Closing as nothing to be done from pyghsheets's side, seems like a change in api behavior.

**Closed by nithinmurali** 2019-10-10 13:08 UTC
Labels: bug

**Comment by devin-moonrise** [comment] 2019-10-31 15:09
@nithinmurali FYI this suddenly started working again last night some time.
