### ISSUE TITLE
SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac

### ISSUE THREAD

**Issue by engrumaraftab** [nithinmurali/pygsheets#291] opened 2018-10-23 03:50 UTC
I have a python script which uses pygsheets to connect to gsheet. The script runs quite well on the Windows Server but throws an exception 'SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac' when running on Ubuntu.
`````import pygsheets
from oauth2client.service_account import ServiceAccountCredentials

scope = [
        'https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive'
         ]

credentials01 = ServiceAccountCredentials.from_json_keyfile_name('creds01.json', scope)
credentials02 = ServiceAccountCredentials.from_json_keyfile_name('creds02.json', scope)

file01 = pygsheets.authorize(credentials=credentials01)
file02 = pygsheets.authorize(credentials=credentials02)
wb01 = file01.open('Database System 2')
wb02 = file02.open('Database System 2')

if __name__ == '__main__':
    manager = multiprocessing.Manager()
    output_dfs = manager.list()
    new_dfs_dict = manager.dict()
    for l in main_list:
        for i in range(0, len(l[0]), 5):
            processes = []
            ids_sublist = []
            for j in range(i, i + 5):
                try:
                    ids_sublist.append(l[0][j])
                except:
                    pass
            for ID in ids_sublist:
                processes.append(multiprocessing.Process(target=fetch_data, args=(ID, start_date, end_date, new_dfs_dict, output_dfs)))
            for p in processes:
                p.start()
            for p in processes:
                p.join()

        for ID in l[0]:
            if not l[1].empty:
                cols_list = list(l[2][ID].columns)
                cols_list.remove('Type')
                cols_list[1:1] = ['Type']
                l[2][ID] = l[2][ID][cols_list]
                l[2][ID].update(new_dfs_dict[ID])
                l[2][ID] = pd.merge(l[2][ID], new_dfs_dict[ID])
            else:
                l[2][ID] = new_dfs_dict[ID]
        ready_to_set_df = pd.DataFrame()
        for ID in l[2]:
            ready_to_set_df = pd.concat([ready_to_set_df, l[2][ID]], sort=False)
            output_sheet = wb01.worksheet_by_title(l[3])            
            output_sheet.clear()
            output_sheet.set_dataframe(ready_to_set_df.fillna(0), 'A1')

    output_df = pd.DataFrame(columns=bank_portal_data_header)
    for df in output_dfs:
        output_df = output_df.append(df)
    try:
        data_sheet = wb02.worksheet_by_title(end_date)
        data_df = data_sheet.get_as_df(has_header=True)
        output_df = data_df[bank_portal_data_header].append(output_df)
        output_df = output_df.drop_duplicates(keep=False)
        data_sheet.clear()
        data_sheet.set_dataframe(output_df, 'A1', copy_head=True)
    except:
        data_sheet = wb02.add_worksheet(end_date)
        data_sheet.set_dataframe(output_df, 'A1', copy_head=True)`````

It first threw the exception at the line data_sheet.clear().
When I commented out this statement, it was at the next line data_sheet.set_dataframe(output_df, 'A1', copy_head=True)

Please help!

**Comment by engrumaraftab** [comment] 2018-10-23 08:36
@nithinmurali 

I just tried with this simple script and it ran good. It printed all the values.

**Comment by engrumaraftab** [comment] 2018-10-23 08:39
In my script, I have employed other functions as well like update_cell(), get_as_df() - cell indexing i.e. ws[i][j]. It doesn't throw exception for any of them. 

Actually, as I mentioned earlier, the script runs well on the Windows Server without throwing any exception. It's just happening on Ubuntu

**Comment by engrumaraftab** [comment] 2018-10-23 08:48
I also tried the following code. Threw no exception. Seems like pygsheets breaks the connection with google api. clear() and set_dataframe() functions are among the last lines of the code. Maybe the connection breaks before the code reaches here.
```
import pygsheets
from oauth2client.service_account import ServiceAccountCredentials
scope = [
        'https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive'
         ]

credentials02 = ServiceAccountCredentials.from_json_keyfile_name('creds02.json', scope)

file02 = pygsheets.authorize(credentials=credentials02)
wb02 = file02.open('Database System 2')
data_sheet = wb02.worksheet_by_title(end_date)

data_sheet.clear()
```

**Comment by engrumaraftab** [comment] 2018-10-23 08:59
Is there a way to keep the connection alive all the time?

**Comment by nithinmurali** [comment] 2018-10-23 09:13
pygsheets dosen't explicity break connection, but maybe google python client does. How long does your script takes to run?

**Comment by engrumaraftab** [comment] 2018-10-23 09:16
It runs for 30 seconds before it hits clear() and set_dataframe() functions

**Comment by engrumaraftab** [comment] 2018-10-23 09:17
Anyway to get around it?

**Comment by nithinmurali** [comment] 2018-10-23 09:30
lemme check if i can recreate the issue

**Comment by engrumaraftab** [comment] 2018-10-23 09:31
I also tried this to connect this way. Now, it gives ConnectionResetError at the same line as before.
```
import pygsheets
from oauth2client.service_account import ServiceAccountCredentials
scope = [
	'https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive'
         ]

credentials01 = ServiceAccountCredentials.from_json_keyfile_name('creds01.json', scope)
file01 = pygsheets.client.Client(credentials01)
```

**Comment by nithinmurali** [comment] 2018-10-23 09:34
you can try changing how you are authorizing
```
file01 = pygsheets.authorize(service_file='creds01.json')
```

**Comment by engrumaraftab** [comment] 2018-10-23 09:36
I did but ConnectionResetError now

**Comment by engrumaraftab** [comment] 2018-10-23 09:40
Not working :(
Again SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac

**Comment by engrumaraftab** [comment] 2018-10-23 09:47
Is there any option like `keep-alive=True` like gspread?

**Comment by nithinmurali** [comment] 2018-10-23 10:11
> Is there any option like keep-alive=True like gspread?

I am afraid not.

**Comment by engrumaraftab** [comment] 2018-10-24 01:29
Hi @nithinmurali 

Did you find a way to get around it?

**Comment by nithinmurali** [comment] 2018-10-24 04:40
Nope, i was unable to reproduce the issue. I have made the http object configurable in Client, you can set the 'set-alive=True' using that.

**Comment by nithinmurali** [comment] 2018-11-12 18:30
closing as issue is fixed, please re-open if it still not solves your problem

**Closed by nithinmurali** 2018-11-12 18:30 UTC

**Comment by samamorgan** [comment] 2021-02-22 18:34
I ended up hitting this same error when trying to make simultaneous requests through one client on multiple threads. The first thread that starts using the client succeeds, but the rest throw this SSLError. I don't have the time at the moment to debug the issue, but thought the additional data point might help track down the problem, especially since OP was using multiprocessing.

**Comment by samamorgan** [comment] 2021-02-26 19:24
Looks like this happens because [httplib2.Http() objects are not thread-safe](https://googleapis.github.io/google-api-python-client/docs/thread_safety.html)

**Comment by samamorgan** [comment] 2021-02-26 19:53
I was able to fix this issue by creating a single client per thread instead of trying to share one client between many threads. The original report by @engrumaraftab could likely be fixed the same way: Instead of clients in global scope, create them as a process-local resource.

**Comment by nithinmurali** [comment] 2021-02-27 10:50
Good catch. I will add this to the docs.

**Comment by felipemaion** [comment] 2023-05-02 12:23
Hi there. I was facing this issue. And after reading @samamorgan's link I've push the code (to staging) fixing this issue.
It is working perfect with multithreading. And all the tests passed.
You can check the diff [here](https://github.com/felipemaion/pygsheets/commit/ccbf1f2ab70809cf2a6da3598a6942b98de538dc)
PS: it is my first contribution to a Github project, please, let me know if I pushed properly the code to your repo, or only to my fork.

Thank you!
