### ISSUE TITLE
update_cells out of range error

### ISSUE THREAD

**Issue by jeffderbyshire** [nithinmurali/pygsheets#132] opened 2017-10-05 20:17 UTC
**When calling the function with:**
update_cells('A3', my_data)

**I get this error:**
 raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/<omitted>/values/Servers%21A3%3AL113?alt=json&valueInputOption=USER_ENTERED returned "Requested writing within range [Servers!A3:L113], but tried writing to column [M]">

My data does vary and I can't predict the number of columns used.

**The work around** 
update_cells('A3:N2000', my_data)
but then I have a lot of empty rows, but no error.
Do I use another parameter in update_cells to make this work?  Or do I need to make sure my data uses a fixed number of columns?

I'm a python newbie.
What does the cell_list parameter do and what is the input format?

Thanks,

Jeff

**Comment by nithinmurali** [comment] 2017-10-05 22:07
Hi Jeff, 

No you dont need to write the exact number of cols. And this should work the way you have used it.  I an unable to reproduce the error you are having. Can you try something simple as 
```
update_cells('A3', [range(5)]*5 )
```
and see it its writing to the exact bounds? Also what is your pygsheets version? make sure you are updated.

cell_list is if you have a list of cell objects (pygsheets.Cell)  and you want to update all of their values, then instead of updating values in each of them you can use this funciton. its more efficient.

**Comment by jeffderbyshire** [comment] 2017-10-05 22:54
The version is pygsheets-1.1.3-py2.6.

Sample data
[...]
[u'host01', u'-2-1437', u'2017-11-11', 'false', u'null', u'3rdThu', u'60', '35 days', u'server',     u'production', u'Name1'],
  3 [u'host01', u'-2-1437', u'2017-11-11', 'false', u'null', u'3rdThu', u'60', '35 days', u'server',     u'production', u'Name1', u'Name2', u'Name3'],
  4 [u'host01', u'-2-1437', u'2017-11-11', 'false', u'null', u'3rdThu', u'60', '35 days', u'server',     u'production', u'Name1', u'Name2'],
  5 [u'host01', u'-2-1437', u'2017-11-11', 'false', u'null', u'3rdThu', u'60', '35 days', u'server',     u'production', u'Name1'],
[...]

Sometimes there are extra columns (list items) in each list.  
I'm using a list of lists and not sure if that's the best way, but I can use .append.

The data is about 3000 lines.  When there is a fixed number of list items (columns) it works perfectly.

**Comment by nithinmurali** [comment] 2017-10-06 22:06
Hey, 
 This should be fixed by now. Please install the staging version and confirm if this works.
```
pip install https://github.com/nithinmurali/pygsheets/archive/staging.zip
```

**Closed** 2017-10-09 12:54 UTC
Labels: bug

**Comment by jeffderbyshire** [comment] 2017-10-10 21:37
Confirmed working.  Thanks.
